# Generated by Django 5.0.6 on 2024-06-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['date_created']},
        ),
    ]
